version: "3"

services:
  dietgpt:
    container_name: dietgpt
    build: .
    command: python -u dietgpt
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "api.dietgpt.gouv.media"
      SITES: "api.dietgpt.gouv.media=dietgpt:8080"

volumes:
  ssl_data:
