version: "3"

services:
  calorily:
    container_name: calorily
    build: .
    command: python -u calorily
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "api.calorily.com"
      SITES: "api.calorily.com=calorily:8080"

volumes:
  ssl_data:
